### DISCUSSION TITLE
Can we set the charge slot?

### DISCUSSION THREAD

**Discussion by oliwarner** [cdpuk/givenergy-local#107] [General]
I've got an inverter with a single charge slot. I'm on an Octopus tariff where my rate dips when our EV is charging (as well as a night time low cost time). The problem I'm facing is I need the battery to charge, and definitely not discharge when the EV is charging.

I can't see anything in the native API that just says "CHARGE NOW!" but you can change the charge slot. This isn't exposed in givenergy-local though, is it?

I'd love to script something via the HA API that interacts with givenergy-local to do this.

**Comment by oliwarner** [comment]
Argl there's a `_async_enable_timed_charge()`

How can I call this?

**Comment by oliwarner** [comment]
Aaaah, it's exposed as a HA service call:

![image](https://github.com/user-attachments/assets/e75018d0-4a21-4979-b818-727c1b2c0c6e)


Okay, I might be able to do this over API.

**Comment by cdpuk** [comment]
You've found the right action. There is also a "Disable timed charging" action to return to normal operation. These are the two actions that I use to solve exactly the same problem.

Assuming Octopus Intelligent Go, for additional discounted charging you can automate based on the "dispatching" sensor, which also reflects any additional off-peak pricing you're given over and above the normal 2330-0500 period.

**Reply by oliwarner** [reply]
Yup, I started with the dispatching sensor, but found that the lag between the Octopus integration updating and then getting the battery to charge (it takes a few minutes) left gaps at the start and end of a discounted period. So now I just track the current rate, and use the current_rate.end attribute to tell the battery to stop charging again. This should also have the benefit of charging up for any free energy sessions.

Here's my whole automation. 

```yaml
alias: Charge battery < 8p
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.octopus_energy_electricity_ACB123_current_rate
conditions: []
actions:
  - if:
      - condition: numeric_state
        entity_id: >-
          sensor.octopus_energy_electricity_ACB123_current_rate
        below: 0.08
    then:
      - action: givenergy_local.enable_timed_charge
        metadata: {}
        data:
          device_id: giv_local_id
          charge_target: 100
          start_time: >-
            {{ (now()|as_timestamp - 60)|timestamp_custom('%H:%M:%S', True)
            }}
          end_time: >-
            {{
            state_attr('sensor.octopus_energy_electricity_ABC123_current_rate',
            'end') | as_timestamp | timestamp_custom('%H:%M:%S', True) }}
    else:
      - action: givenergy_local.enable_timed_charge
        metadata: {}
        data:
          device_id: giv_local_id
          charge_target: 100
          start_time: "23:30:00"
          end_time: "05:30:00"
mode: single
```
